services:
  mysql:
    image: mysql:8.4
    environment:
      MYSQL_DATABASE: urlshortener
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - mysqldata:/var/lib/mysql

volumes:
  mysqldata: